sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t vorbrodt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vorbrodt/docker-react npm run test