sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t vorbrodt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vorbrodt/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: "docker-react" 
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-355767558195"
  bucket_path: "docker-react"
  on:
    branch: main #do deploy when we push to master branch
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"